### ISSUE TITLE
bug: Приложение не отвечает, после вызова команды с неограниченным временем действия

### ISSUE THREAD

**Issue by Konstantin-Velichkovsky** [EndoTouma/ADB_Controller#4]
Раздел: Control

Проблема возникает после вызова команды logcat > "C:\jpay_log\log.log" которая имеет неограниченное по времени действие, а именно запись лога с устройства в файл. Команда на устройстве выполняется корректно, но приложение перестает отвечать.

![image](https://github.com/EndoTouma/ADB_Controller/assets/173891609/bf2c3df5-d5a9-4a3b-974e-b6a998fd8fd5)

Ожидаемое: После выполнения команды должно появится окно, с помощью которого можно будет прервать ранее вызванную команду с помощью кнопки "Stop", и ограничить возможность использования других функций приложения, до тех пор пока пользователь не остановит выполнение команды.

**Comment by EndoTouma** [comment]
https://github.com/EndoTouma/ADB_Controller/releases/tag/v2.0.0 исправлено тут
