### ISSUE TITLE
feature: Добавить возможность выбора файла при вызове команды установки

### ISSUE THREAD

**Issue by Konstantin-Velichkovsky** [EndoTouma/ADB_Controller#7]
Раздел: Control

Добавить возможность выбора файла при вызове команды установки adb install, на данный момент возможно только вручную прописывать полный путь до файла в команде.

![image](https://github.com/EndoTouma/ADB_Controller/assets/173891609/f03a7d5b-5521-4b7c-9362-f421cee9b800)

Необходимо сделать, после вызова команды adb install -r без указанного пути файла, вывод окна проводника для выбора файла для установки, по аналогии как это сделано в функции logcat to file.

Также, если возможно использовать дополнительно метод drag&drop для выбора файла установки

**Comment by EndoTouma** [comment]
добавлено в https://github.com/EndoTouma/ADB_Controller/pull/9
